/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as QuizRouteImport } from './routes/quiz/route'
import { Route as IndexImport } from './routes/index'
import { Route as QuizNewImport } from './routes/quiz/new'
import { Route as QuizQuizIdImport } from './routes/quiz/$quizId'
import { Route as QuizQuizIdResultsImport } from './routes/quiz/$quizId.results'

// Create/Update Routes

const QuizRouteRoute = QuizRouteImport.update({
  id: '/quiz',
  path: '/quiz',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const QuizNewRoute = QuizNewImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => QuizRouteRoute,
} as any)

const QuizQuizIdRoute = QuizQuizIdImport.update({
  id: '/$quizId',
  path: '/$quizId',
  getParentRoute: () => QuizRouteRoute,
} as any)

const QuizQuizIdResultsRoute = QuizQuizIdResultsImport.update({
  id: '/results',
  path: '/results',
  getParentRoute: () => QuizQuizIdRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/quiz': {
      id: '/quiz'
      path: '/quiz'
      fullPath: '/quiz'
      preLoaderRoute: typeof QuizRouteImport
      parentRoute: typeof rootRoute
    }
    '/quiz/$quizId': {
      id: '/quiz/$quizId'
      path: '/$quizId'
      fullPath: '/quiz/$quizId'
      preLoaderRoute: typeof QuizQuizIdImport
      parentRoute: typeof QuizRouteImport
    }
    '/quiz/new': {
      id: '/quiz/new'
      path: '/new'
      fullPath: '/quiz/new'
      preLoaderRoute: typeof QuizNewImport
      parentRoute: typeof QuizRouteImport
    }
    '/quiz/$quizId/results': {
      id: '/quiz/$quizId/results'
      path: '/results'
      fullPath: '/quiz/$quizId/results'
      preLoaderRoute: typeof QuizQuizIdResultsImport
      parentRoute: typeof QuizQuizIdImport
    }
  }
}

// Create and export the route tree

interface QuizQuizIdRouteChildren {
  QuizQuizIdResultsRoute: typeof QuizQuizIdResultsRoute
}

const QuizQuizIdRouteChildren: QuizQuizIdRouteChildren = {
  QuizQuizIdResultsRoute: QuizQuizIdResultsRoute,
}

const QuizQuizIdRouteWithChildren = QuizQuizIdRoute._addFileChildren(
  QuizQuizIdRouteChildren,
)

interface QuizRouteRouteChildren {
  QuizQuizIdRoute: typeof QuizQuizIdRouteWithChildren
  QuizNewRoute: typeof QuizNewRoute
}

const QuizRouteRouteChildren: QuizRouteRouteChildren = {
  QuizQuizIdRoute: QuizQuizIdRouteWithChildren,
  QuizNewRoute: QuizNewRoute,
}

const QuizRouteRouteWithChildren = QuizRouteRoute._addFileChildren(
  QuizRouteRouteChildren,
)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/quiz': typeof QuizRouteRouteWithChildren
  '/quiz/$quizId': typeof QuizQuizIdRouteWithChildren
  '/quiz/new': typeof QuizNewRoute
  '/quiz/$quizId/results': typeof QuizQuizIdResultsRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/quiz': typeof QuizRouteRouteWithChildren
  '/quiz/$quizId': typeof QuizQuizIdRouteWithChildren
  '/quiz/new': typeof QuizNewRoute
  '/quiz/$quizId/results': typeof QuizQuizIdResultsRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/quiz': typeof QuizRouteRouteWithChildren
  '/quiz/$quizId': typeof QuizQuizIdRouteWithChildren
  '/quiz/new': typeof QuizNewRoute
  '/quiz/$quizId/results': typeof QuizQuizIdResultsRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/quiz'
    | '/quiz/$quizId'
    | '/quiz/new'
    | '/quiz/$quizId/results'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/quiz' | '/quiz/$quizId' | '/quiz/new' | '/quiz/$quizId/results'
  id:
    | '__root__'
    | '/'
    | '/quiz'
    | '/quiz/$quizId'
    | '/quiz/new'
    | '/quiz/$quizId/results'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  QuizRouteRoute: typeof QuizRouteRouteWithChildren
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  QuizRouteRoute: QuizRouteRouteWithChildren,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/quiz"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/quiz": {
      "filePath": "quiz/route.tsx",
      "children": [
        "/quiz/$quizId",
        "/quiz/new"
      ]
    },
    "/quiz/$quizId": {
      "filePath": "quiz/$quizId.tsx",
      "parent": "/quiz",
      "children": [
        "/quiz/$quizId/results"
      ]
    },
    "/quiz/new": {
      "filePath": "quiz/new.tsx",
      "parent": "/quiz"
    },
    "/quiz/$quizId/results": {
      "filePath": "quiz/$quizId.results.tsx",
      "parent": "/quiz/$quizId"
    }
  }
}
ROUTE_MANIFEST_END */
